apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-frontend
  namespace: course-registration
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-frontend
  template:
    metadata:
      labels:
        app: react-frontend
    spec:
      containers:
      - name: react-frontend
        image: asia-south1-docker.pkg.dev/women-safety-by-pioneers/course-registration/react-frontend:1.0 
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: react-frontend-service
  namespace: course-registration
spec:
  type: LoadBalancer
  selector:
    app: react-frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: react-frontend-hpa
  namespace: course-registration
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: react-frontend
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70